'use strict';

module.exports = [
  { indent: 0, name: 'etc',                                                 uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 1, name: 'resolv.conf',                                         uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1512117562000), ctime: null, length: 75 },
  { indent: 1, name: 'runlevels',                                           uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 2, name: 'shutdown',                                            uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 3, name: 'savecache',                                           uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/savecache' },
  { indent: 3, name: 'killprocs',                                           uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/killprocs' },
  { indent: 3, name: 'mount-ro',                                            uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/mount-ro' },
  { indent: 2, name: 'boot',                                                uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 3, name: 'syslog',                                              uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/syslog' },
  { indent: 3, name: 'bootmisc',                                            uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/bootmisc' },
  { indent: 3, name: 'hostname',                                            uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/hostname' },
  { indent: 3, name: 'modules',                                             uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/modules' },
  { indent: 3, name: 'sysctl',                                              uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/sysctl' },
  { indent: 3, name: 'networking',                                          uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/networking' },
  { indent: 3, name: 'urandom',                                             uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/urandom' },
  { indent: 3, name: 'swclock',                                             uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/swclock' },
  { indent: 2, name: 'sysinit',                                             uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 3, name: 'dmesg',                                               uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/dmesg' },
  { indent: 3, name: 'devfs',                                               uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/devfs' },
  { indent: 3, name: 'modloop',                                             uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/modloop' },
  { indent: 3, name: 'hwdrivers',                                           uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/hwdrivers' },
  { indent: 3, name: 'mdev',                                                uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/mdev' },
  { indent: 2, name: 'default',                                             uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 3, name: 'acpid',                                               uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/acpid' },
  { indent: 3, name: 'crond',                                               uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/crond' },
  { indent: 3, name: 'sshd',                                                uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/sshd' },
  { indent: 3, name: 'chronyd',                                             uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/init.d/chronyd' },
  { indent: 1, name: 'hostname',                                            uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19252000), ctime: null, length: 10 },
  { indent: 1, name: 'network',                                             uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 2, name: 'interfaces',                                          uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19295000), ctime: null, length: 84 },
  { indent: 1, name: 'securetty',                                           uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(7000), ctime: null, length: 73 },
  { indent: 1, name: 'fstab',                                               uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1508427162000), ctime: null, length: 182 },
  { indent: 1, name: 'inittab',                                             uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(7000), ctime: null, length: 661 },
  { indent: 1, name: 'lbu',                                                 uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 2, name: 'lbu.conf',                                            uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1508427162000), ctime: null, length: 498 },
  { indent: 1, name: 'zoneinfo',                                            uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: new Date(5000), ctime: null, dir: true },
  { indent: 2, name: 'Europe',                                              uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: new Date(5000), ctime: null, dir: true },
  { indent: 3, name: 'Paris',                                               uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19370000), ctime: null, length: 2971 },
  { indent: 1, name: 'localtime',                                           uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/etc/zoneinfo/Europe/Paris' },
  { indent: 1, name: 'hosts',                                               uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19374000), ctime: null, length: 83 },
  { indent: 1, name: 'ssh',                                                 uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 2, name: 'sshd_config',                                         uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1508427525000), ctime: null, length: 3427 },
  { indent: 2, name: 'ssh_host_rsa_key',                                    uid: 0, gid: 0,  mode: 0o600, atime: null, mtime: new Date(19428000), ctime: null, length: 1679 },
  { indent: 2, name: 'ssh_host_rsa_key.pub',                                uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19428000), ctime: null, length: 396 },
  { indent: 2, name: 'ssh_host_dsa_key',                                    uid: 0, gid: 0,  mode: 0o600, atime: null, mtime: new Date(19433000), ctime: null, length: 668 },
  { indent: 2, name: 'ssh_host_dsa_key.pub',                                uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19433000), ctime: null, length: 604 },
  { indent: 2, name: 'ssh_host_ecdsa_key',                                  uid: 0, gid: 0,  mode: 0o600, atime: null, mtime: new Date(19433000), ctime: null, length: 227 },
  { indent: 2, name: 'ssh_host_ecdsa_key.pub',                              uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19433000), ctime: null, length: 176 },
  { indent: 2, name: 'ssh_host_ed25519_key',                                uid: 0, gid: 0,  mode: 0o600, atime: null, mtime: new Date(19433000), ctime: null, length: 411 },
  { indent: 2, name: 'ssh_host_ed25519_key.pub',                            uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19433000), ctime: null, length: 96 },
  { indent: 1, name: 'group-',                                              uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19440000), ctime: null, length: 711 },
  { indent: 1, name: 'group',                                               uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19440000), ctime: null, length: 717 },
  { indent: 1, name: 'shadow-',                                             uid: 0, gid: 42, mode: 0o640, atime: null, mtime: new Date(19440000), ctime: null, length: 571 },
  { indent: 1, name: 'shadow',                                              uid: 0, gid: 42, mode: 0o640, atime: null, mtime: new Date(1508427598000), ctime: null, length: 575 },
  { indent: 1, name: 'passwd-',                                             uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(19440000), ctime: null, length: 1278 },
  { indent: 1, name: 'passwd',                                              uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1508427598000), ctime: null, length: 1278 },
  { indent: 1, name: 'apk',                                                 uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 2, name: 'world',                                               uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1512119211000), ctime: null, length: 27 },
  { indent: 2, name: 'arch',                                                uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(5000), ctime: null, length: 6 },
  { indent: 2, name: 'keys',                                                uid: 0, gid: 0,  mode: 0o755, atime: null, mtime: null, ctime: null, dir: true, missing: true },
  { indent: 3, name: 'alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub', uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1497692775000), ctime: null, length: 451 },
  { indent: 3, name: 'alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub', uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1497692775000), ctime: null, length: 451 },
  { indent: 2, name: 'repositories',                                        uid: 0, gid: 0,  mode: 0o644, atime: null, mtime: new Date(1512119193000), ctime: null, length: 275 },
  { indent: 2, name: 'cache',                                               uid: 0, gid: 0,  mode: 0o777, atime: null, mtime: new Date(5000), ctime: null, target: '/media/mmcblk0p1/cache' },
];