import DescriptionIcon from '@material-ui/icons/Description';
import PlayArrowIcon from '@material-ui/icons/PlayArrow';
import CheckIcon from '@material-ui/icons/Check';
import CloseIcon from '@material-ui/icons/Close';
import PlaylistPlayIcon from '@material-ui/icons/PlaylistPlay';
import FolderOpenIcon from '@material-ui/icons/FolderOpen';
import DeleteIcon from '@material-ui/icons/Delete';
import LocationOnIcon from '@material-ui/icons/LocationOn';
import LocationOffIcon from '@material-ui/icons/LocationOff';

export const RecipeIcon = DescriptionIcon;
export const StartIcon = PlayArrowIcon;
export const RunsIcon = PlaylistPlayIcon;
export const RunningIcon = PlayArrowIcon;
export const SuccessIcon = CheckIcon;
export const FailureIcon = CloseIcon;
export const FileIcon = FolderOpenIcon;
export { DeleteIcon };
export const PinIcon = LocationOnIcon;
export const UnpinIcon = LocationOffIcon;